services:
  n8n:
    image: n8nio/n8n
    ports:
      - 5678:5678
    env_file:
      - .env
    environment:
      - N8N_CORS_ALLOW_ORIGIN=*
    volumes:
      - ~/.n8n:/home/node/.n8n

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cctv_traffic_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mini-project/db/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
    ports:
      - "3306:3306"

volumes:
  db_data: